import { z } from "zod";
import {
  V1AuthContextResponse,
  V1AuthDeviceListResponse,
  V1AuthDeviceRevokeRequest,
  V1AuthDeviceRevokeResponse,
  V1AuthSignOutRequest,
  V1AuthSignOutResponse,
  V1DeletionCancelRequest,
  V1DeletionCancelResponse,
  V1DeletionImpactResponse,
  V1DeletionRequestRequest,
  V1DeletionRequestResponse,
  V1IdentityLinkRequest,
  V1IdentityLinkResponse,
  V1IdentityUnlinkRequest,
  V1IdentityUnlinkResponse,
  V1ReauthChallengeRequest,
  V1ReauthChallengeResponse,
  V1ReauthVerifyRequest,
  V1ReauthVerifyResponse,
} from "./auth";
import { V1MeResponse } from "./me";
import type { IdempotencyMode } from "./platform";
import * as Academic from "./academic";
import * as SchoolAdmin from "./schoolAdmin";
import * as Invitations from "./invitations";
import * as Family from "./family";
import * as Communications from "./communications";
import * as Meetings from "./meetings";
import * as Notifications from "./notifications";
import * as Account from "./account";
import * as SupportAccess from "./supportAccess";
import * as Safety from "./safety";
import * as Files from "./files";

export interface V1RouteContract {
  method: "get" | "post";
  path: string;
  operationId: string;
  summary: string;
  permission: string;
  idempotency: IdempotencyMode;
  successStatus?: 200 | 201;
  params?: z.ZodType;
  paramsSchema?: string;
  query?: z.ZodType;
  querySchema?: string;
  request?: z.ZodType;
  requestSchema?: string;
  response: z.ZodType;
  responseSchema: string;
}

/** Canonical inventory for every implemented /v1 handler. */
export const V1_ROUTE_CATALOGUE = [
  {
    method: "get",
    path: "/v1/me",
    operationId: "getMe",
    summary: "Authenticated profile and tenant memberships",
    permission: "account.profile.read",
    idempotency: "none",
    response: V1MeResponse,
    responseSchema: "V1MeResponse",
  },
  {
    method: "get",
    path: "/v1/auth/context",
    operationId: "getAuthContext",
    summary: "Server-derived tenant and role context",
    permission: "account.context.read",
    idempotency: "none",
    response: V1AuthContextResponse,
    responseSchema: "V1AuthContextResponse",
  },
  {
    method: "get",
    path: "/v1/auth/devices",
    operationId: "listAuthDevices",
    summary: "Devices that have held a session for this account",
    permission: "account.devices.read",
    idempotency: "none",
    response: V1AuthDeviceListResponse,
    responseSchema: "V1AuthDeviceListResponse",
  },
  {
    method: "post",
    path: "/v1/auth/devices/revoke",
    operationId: "revokeAuthDevice",
    summary: "Revoke one owned device",
    permission: "account.device.revoke",
    idempotency: "required",
    request: V1AuthDeviceRevokeRequest,
    requestSchema: "V1AuthDeviceRevokeRequest",
    response: V1AuthDeviceRevokeResponse,
    responseSchema: "V1AuthDeviceRevokeResponse",
  },
  {
    method: "post",
    path: "/v1/auth/sign-out",
    operationId: "signOut",
    summary: "Revoke the current or every session",
    permission: "account.session.revoke",
    idempotency: "required",
    request: V1AuthSignOutRequest,
    requestSchema: "V1AuthSignOutRequest",
    response: V1AuthSignOutResponse,
    responseSchema: "V1AuthSignOutResponse",
  },
  {
    method: "post",
    path: "/v1/auth/reauth/challenge",
    operationId: "challengeReauth",
    summary: "Describe the assurance required for a privileged action",
    permission: "account.reauth.challenge",
    idempotency: "required",
    request: V1ReauthChallengeRequest,
    requestSchema: "V1ReauthChallengeRequest",
    response: V1ReauthChallengeResponse,
    responseSchema: "V1ReauthChallengeResponse",
  },
  {
    method: "post",
    path: "/v1/auth/reauth/verify",
    operationId: "verifyReauth",
    summary: "Issue a single-use recent-authentication grant",
    permission: "account.reauth.verify",
    idempotency: "forbidden",
    request: V1ReauthVerifyRequest,
    requestSchema: "V1ReauthVerifyRequest",
    response: V1ReauthVerifyResponse,
    responseSchema: "V1ReauthVerifyResponse",
  },
  {
    method: "post",
    path: "/v1/auth/identities/link",
    operationId: "linkIdentity",
    summary: "Link a verified sign-in identity",
    permission: "account.identity.link",
    idempotency: "required",
    request: V1IdentityLinkRequest,
    requestSchema: "V1IdentityLinkRequest",
    response: V1IdentityLinkResponse,
    responseSchema: "V1IdentityLinkResponse",
  },
  {
    method: "post",
    path: "/v1/auth/identities/unlink",
    operationId: "unlinkIdentity",
    summary: "Unlink a sign-in identity",
    permission: "account.identity.unlink",
    idempotency: "required",
    request: V1IdentityUnlinkRequest,
    requestSchema: "V1IdentityUnlinkRequest",
    response: V1IdentityUnlinkResponse,
    responseSchema: "V1IdentityUnlinkResponse",
  },
  {
    method: "get",
    path: "/v1/account/deletion-impact",
    operationId: "getDeletionImpact",
    summary: "Preview the effect of account deletion",
    permission: "account.deletion.impact",
    idempotency: "none",
    response: V1DeletionImpactResponse,
    responseSchema: "V1DeletionImpactResponse",
  },
  {
    method: "post",
    path: "/v1/account/deletion-request",
    operationId: "requestAccountDeletion",
    summary: "Schedule account deletion",
    permission: "account.deletion.request",
    idempotency: "required",
    request: V1DeletionRequestRequest,
    requestSchema: "V1DeletionRequestRequest",
    response: V1DeletionRequestResponse,
    responseSchema: "V1DeletionRequestResponse",
  },
  {
    method: "post",
    path: "/v1/account/deletion-cancel",
    operationId: "cancelAccountDeletion",
    summary: "Cancel a pending account deletion",
    permission: "account.deletion.cancel",
    idempotency: "required",
    request: V1DeletionCancelRequest,
    requestSchema: "V1DeletionCancelRequest",
    response: V1DeletionCancelResponse,
    responseSchema: "V1DeletionCancelResponse",
  },
  academicGet(
    "getSchool",
    "/v1/schools/{schoolId}",
    "school.read",
    Academic.V1School,
    "V1School",
    schoolParams(),
  ),
  academicGet(
    "listTerms",
    "/v1/schools/{schoolId}/terms",
    "term.list",
    Academic.V1TermPage,
    "V1TermPage",
    schoolParams(),
    Academic.V1PageQuery,
  ),
  academicGet(
    "listClassrooms",
    "/v1/classrooms",
    "classroom.list",
    Academic.V1ClassroomPage,
    "V1ClassroomPage",
    undefined,
    Academic.V1PageQuery,
  ),
  academicPost(
    "createClassroom",
    "/v1/classrooms",
    "classroom.create",
    Academic.V1CreateClassroomRequest,
    "V1CreateClassroomRequest",
    Academic.V1AcademicClassroom,
    "V1AcademicClassroom",
    201,
  ),
  academicGet(
    "getClassroom",
    "/v1/classrooms/{classroomId}",
    "classroom.read",
    Academic.V1ClassroomDetail,
    "V1ClassroomDetail",
    classroomParams(),
  ),
  academicGet(
    "listClassroomStaff",
    "/v1/classrooms/{classroomId}/staff",
    "classroom.staff.read",
    Academic.V1ClassroomStaffPage,
    "V1ClassroomStaffPage",
    classroomParams(),
    Academic.V1PageQuery,
  ),
  academicPost(
    "updateClassroom",
    "/v1/classrooms/{classroomId}/update",
    "classroom.update",
    Academic.V1UpdateClassroomRequest,
    "V1UpdateClassroomRequest",
    Academic.V1AcademicClassroom,
    "V1AcademicClassroom",
    200,
    classroomParams(),
  ),
  academicPost(
    "replaceClassroomSchedule",
    "/v1/classrooms/{classroomId}/schedule/replace",
    "classroom.schedule.write",
    Academic.V1ReplaceScheduleRequest,
    "V1ReplaceScheduleRequest",
    Academic.V1ClassroomDetail,
    "V1ClassroomDetail",
    200,
    classroomParams(),
  ),
  academicGet(
    "listClassroomStudents",
    "/v1/classrooms/{classroomId}/students",
    "classroom.roster.read",
    Academic.V1StudentPage,
    "V1StudentPage",
    classroomParams(),
    Academic.V1PageQuery,
  ),
  academicGet(
    "listResources",
    "/v1/resources",
    "resource.list",
    Academic.V1ResourcePage,
    "V1ResourcePage",
    undefined,
    Academic.V1PageQuery,
  ),
  academicGet(
    "listLessonSessions",
    "/v1/lesson-sessions",
    "lesson_session.list",
    Academic.V1LessonSessionPage,
    "V1LessonSessionPage",
    undefined,
    Academic.V1PageQuery,
  ),
  academicPost(
    "createResource",
    "/v1/resources",
    "resource.create",
    Academic.V1CreateResourceRequest,
    "V1CreateResourceRequest",
    Academic.V1Resource,
    "V1Resource",
    201,
  ),
  academicPost(
    "reviseResource",
    "/v1/resources/{resourceId}/revise",
    "resource.revise",
    Academic.V1ReviseResourceRequest,
    "V1ReviseResourceRequest",
    Academic.V1Resource,
    "V1Resource",
    200,
    resourceParams(),
  ),
  academicPost(
    "publishResource",
    "/v1/resources/{resourceId}/publish",
    "resource.publish",
    Academic.V1VersionCommandRequest,
    "V1VersionCommandRequest",
    Academic.V1Resource,
    "V1Resource",
    200,
    resourceParams(),
  ),
  academicPost(
    "withdrawResource",
    "/v1/resources/{resourceId}/withdraw",
    "resource.withdraw",
    Academic.V1VersionCommandRequest,
    "V1VersionCommandRequest",
    Academic.V1Resource,
    "V1Resource",
    200,
    resourceParams(),
  ),
  academicGet(
    "listAssignments",
    "/v1/assignments",
    "assignment.list",
    Academic.V1AssignmentPage,
    "V1AssignmentPage",
    undefined,
    Academic.V1PageQuery,
  ),
  academicPost(
    "createAssignment",
    "/v1/assignments",
    "assignment.create",
    Academic.V1CreateAssignmentRequest,
    "V1CreateAssignmentRequest",
    Academic.V1Assignment,
    "V1Assignment",
    201,
  ),
  academicPost(
    "publishAssignment",
    "/v1/assignments/{assignmentId}/publish",
    "assignment.publish",
    Academic.V1VersionCommandRequest,
    "V1VersionCommandRequest",
    Academic.V1Assignment,
    "V1Assignment",
    200,
    assignmentParams(),
  ),
  academicPost(
    "withdrawAssignment",
    "/v1/assignments/{assignmentId}/withdraw",
    "assignment.withdraw",
    Academic.V1VersionCommandRequest,
    "V1VersionCommandRequest",
    Academic.V1Assignment,
    "V1Assignment",
    200,
    assignmentParams(),
  ),
  academicPost(
    "submitAssignment",
    "/v1/assignments/{assignmentId}/submit",
    "assignment.submit",
    Academic.V1SubmitAssignmentRequest,
    "V1SubmitAssignmentRequest",
    Academic.V1Submission,
    "V1Submission",
    201,
    assignmentParams(),
  ),
  academicGet(
    "getAssignment",
    "/v1/assignments/{assignmentId}",
    "assignment.read",
    Academic.V1Assignment,
    "V1Assignment",
    assignmentParams(),
  ),
  academicGet(
    "listAssignmentSubmissions",
    "/v1/assignments/{assignmentId}/submissions",
    "submission.list",
    Academic.V1SubmissionPage,
    "V1SubmissionPage",
    assignmentParams(),
    Academic.V1PageQuery,
  ),
  academicGet(
    "listAssessments",
    "/v1/assessments",
    "assessment.list",
    Academic.V1AssessmentPage,
    "V1AssessmentPage",
    undefined,
    Academic.V1PageQuery,
  ),
  academicPost(
    "createAssessment",
    "/v1/assessments",
    "assessment.create",
    Academic.V1CreateAssessmentRequest,
    "V1CreateAssessmentRequest",
    Academic.V1Assessment,
    "V1Assessment",
    201,
  ),
  academicPost(
    "publishAssessment",
    "/v1/assessments/{assessmentId}/publish",
    "assessment.publish",
    Academic.V1VersionCommandRequest,
    "V1VersionCommandRequest",
    Academic.V1Assessment,
    "V1Assessment",
    200,
    assessmentParams(),
  ),
  academicPost(
    "withdrawAssessment",
    "/v1/assessments/{assessmentId}/withdraw",
    "assessment.withdraw",
    Academic.V1VersionCommandRequest,
    "V1VersionCommandRequest",
    Academic.V1Assessment,
    "V1Assessment",
    200,
    assessmentParams(),
  ),
  academicGet(
    "listAssessmentQuestions",
    "/v1/assessments/{assessmentId}/questions",
    "assessment_question.list",
    Academic.V1AssessmentQuestionsResponse,
    "V1AssessmentQuestionsResponse",
    assessmentParams(),
    Academic.V1PageQuery,
  ),
  academicGet(
    "listAssessmentAuthoringQuestions",
    "/v1/assessments/{assessmentId}/authoring-questions",
    "assessment_question.authoring.list",
    Academic.V1AssessmentAuthoringQuestionsResponse,
    "V1AssessmentAuthoringQuestionsResponse",
    assessmentParams(),
    Academic.V1PageQuery,
  ),
  academicGet(
    "listAssessmentAttempts",
    "/v1/assessments/{assessmentId}/attempts",
    "assessment_attempt.list",
    Academic.V1AssessmentAttemptPage,
    "V1AssessmentAttemptPage",
    assessmentParams(),
    Academic.V1PageQuery,
  ),
  academicPost(
    "submitAssessment",
    "/v1/assessments/{assessmentId}/submit",
    "assessment.submit",
    Academic.V1SubmitAssessmentRequest,
    "V1SubmitAssessmentRequest",
    Academic.V1AssessmentAttempt,
    "V1AssessmentAttempt",
    201,
    assessmentParams(),
  ),
  academicGet(
    "listGradeResults",
    "/v1/grade-results",
    "grade_result.list",
    Academic.V1GradeResultPage,
    "V1GradeResultPage",
    undefined,
    Academic.V1PageQuery,
  ),
  academicPost(
    "reviewGradeResult",
    "/v1/grade-results/{gradeResultId}/review",
    "grade_result.review",
    Academic.V1ReviewGradeRequest,
    "V1ReviewGradeRequest",
    Academic.V1GradeResult,
    "V1GradeResult",
    200,
    gradeParams(),
  ),
  academicPost(
    "publishGradeResult",
    "/v1/grade-results/{gradeResultId}/publish",
    "grade_result.publish",
    Academic.V1VersionCommandRequest,
    "V1VersionCommandRequest",
    Academic.V1GradeResult,
    "V1GradeResult",
    200,
    gradeParams(),
  ),
  academicPost(
    "correctGradeResult",
    "/v1/grade-results/{gradeResultId}/correct",
    "grade_result.correct",
    Academic.V1CorrectGradeRequest,
    "V1CorrectGradeRequest",
    Academic.V1GradeResult,
    "V1GradeResult",
    200,
    gradeParams(),
  ),
  academicPost(
    "withdrawGradeResult",
    "/v1/grade-results/{gradeResultId}/withdraw",
    "grade_result.withdraw",
    Academic.V1VersionCommandRequest,
    "V1VersionCommandRequest",
    Academic.V1GradeResult,
    "V1GradeResult",
    200,
    gradeParams(),
  ),
  academicGet(
    "listAttendance",
    "/v1/attendance",
    "attendance_record.list",
    Academic.V1AttendancePage,
    "V1AttendancePage",
    undefined,
    Academic.V1PageQuery,
  ),
  academicGet(
    "listAttendanceRoster",
    "/v1/classrooms/{classroomId}/attendance-roster",
    "attendance_roster.read",
    Academic.V1AttendanceRosterPage,
    "V1AttendanceRosterPage",
    classroomParams(),
    Academic.V1PageQuery,
  ),
  academicPost(
    "recordAttendance",
    "/v1/attendance/record",
    "attendance_record.write",
    Academic.V1RecordAttendanceRequest,
    "V1RecordAttendanceRequest",
    Academic.V1RecordAttendanceResponse,
    "V1RecordAttendanceResponse",
    200,
  ),
  academicGet(
    "listWellbeing",
    "/v1/wellbeing",
    "wellbeing_event.list",
    Academic.V1WellbeingPage,
    "V1WellbeingPage",
    undefined,
    Academic.V1PageQuery,
  ),
  academicPost(
    "createWellbeing",
    "/v1/wellbeing",
    "wellbeing_event.create",
    Academic.V1CreateWellbeingRequest,
    "V1CreateWellbeingRequest",
    Academic.V1WellbeingEvent,
    "V1WellbeingEvent",
    201,
  ),
  academicPost(
    "provisionSchool",
    "/v1/schools",
    "school.provision",
    SchoolAdmin.V1ProvisionSchoolRequest,
    "V1ProvisionSchoolRequest",
    SchoolAdmin.V1SchoolAdmin,
    "V1SchoolAdmin",
    201,
  ),
  academicPost(
    "suspendSchool",
    "/v1/schools/{schoolId}/suspend",
    "school.suspend",
    SchoolAdmin.V1SchoolLifecycleRequest,
    "V1SchoolLifecycleRequest",
    SchoolAdmin.V1SchoolAdmin,
    "V1SchoolAdmin",
    200,
    schoolParams(),
  ),
  academicPost(
    "closeSchool",
    "/v1/schools/{schoolId}/close",
    "school.close",
    SchoolAdmin.V1SchoolLifecycleRequest,
    "V1SchoolLifecycleRequest",
    SchoolAdmin.V1SchoolAdmin,
    "V1SchoolAdmin",
    200,
    schoolParams(),
  ),
  academicPost(
    "grantMembership",
    "/v1/schools/{schoolId}/memberships/grant",
    "membership.grant",
    SchoolAdmin.V1GrantMembershipRequest,
    "V1GrantMembershipRequest",
    SchoolAdmin.V1MembershipRecord,
    "V1MembershipRecord",
    201,
    schoolParams(),
  ),
  academicPost(
    "activateMembership",
    "/v1/memberships/{membershipId}/activate",
    "membership.activate",
    SchoolAdmin.V1MembershipLifecycleRequest,
    "V1MembershipLifecycleRequest",
    SchoolAdmin.V1MembershipRecord,
    "V1MembershipRecord",
    200,
    membershipParams(),
  ),
  academicPost(
    "suspendMembership",
    "/v1/memberships/{membershipId}/suspend",
    "membership.suspend",
    SchoolAdmin.V1MembershipLifecycleRequest,
    "V1MembershipLifecycleRequest",
    SchoolAdmin.V1MembershipRecord,
    "V1MembershipRecord",
    200,
    membershipParams(),
  ),
  academicPost(
    "revokeMembership",
    "/v1/memberships/{membershipId}/revoke",
    "membership.revoke",
    SchoolAdmin.V1MembershipLifecycleRequest,
    "V1MembershipLifecycleRequest",
    SchoolAdmin.V1MembershipRecord,
    "V1MembershipRecord",
    200,
    membershipParams(),
  ),
  academicPost(
    "assignClassroomStaff",
    "/v1/classrooms/{classroomId}/staff/assign",
    "classroom_staff.write",
    SchoolAdmin.V1AssignClassroomStaffRequest,
    "V1AssignClassroomStaffRequest",
    SchoolAdmin.V1ClassroomStaffAssignment,
    "V1ClassroomStaffAssignment",
    201,
    classroomParams(),
  ),
  academicPost(
    "removeClassroomStaff",
    "/v1/classrooms/{classroomId}/staff/remove",
    "classroom_staff.write",
    SchoolAdmin.V1RemoveClassroomStaffRequest,
    "V1RemoveClassroomStaffRequest",
    SchoolAdmin.V1ClassroomStaffAssignment,
    "V1ClassroomStaffAssignment",
    200,
    classroomParams(),
  ),
  academicPost(
    "enrollStudent",
    "/v1/classrooms/{classroomId}/enrollments/enroll",
    "enrollment.write",
    SchoolAdmin.V1EnrollStudentRequest,
    "V1EnrollStudentRequest",
    SchoolAdmin.V1EnrollmentTransition,
    "V1EnrollmentTransition",
    200,
    classroomParams(),
  ),
  academicPost(
    "withdrawStudent",
    "/v1/classrooms/{classroomId}/enrollments/withdraw",
    "enrollment.write",
    SchoolAdmin.V1WithdrawStudentRequest,
    "V1WithdrawStudentRequest",
    SchoolAdmin.V1EnrollmentTransition,
    "V1EnrollmentTransition",
    200,
    classroomParams(),
  ),
  academicPost(
    "transferEnrollment",
    "/v1/classrooms/{classroomId}/enrollments/transfer",
    "enrollment.write",
    SchoolAdmin.V1TransferEnrollmentRequest,
    "V1TransferEnrollmentRequest",
    SchoolAdmin.V1EnrollmentTransition,
    "V1EnrollmentTransition",
    200,
    classroomParams(),
  ),
  academicPost(
    "issueInvitation",
    "/v1/schools/{schoolId}/invitations",
    "invitation.issue",
    Invitations.V1IssueInvitationRequest,
    "V1IssueInvitationRequest",
    Invitations.V1IssueInvitationResponse,
    "V1IssueInvitationResponse",
    201,
    schoolParams(),
  ),
  academicGet(
    "listInvitations",
    "/v1/schools/{schoolId}/invitations",
    "invitation.list",
    Invitations.V1InvitationPage,
    "V1InvitationPage",
    schoolParams(),
    Academic.V1PageQuery,
  ),
  academicPost(
    "revokeInvitation",
    "/v1/invitations/{invitationId}/revoke",
    "invitation.revoke",
    Invitations.V1RevokeInvitationRequest,
    "V1RevokeInvitationRequest",
    Invitations.V1Invitation,
    "V1Invitation",
    200,
    invitationParams(),
  ),
  academicPost(
    "acceptInvitation",
    "/v1/invitations/accept",
    "invitation.accept",
    Invitations.V1AcceptInvitationRequest,
    "V1AcceptInvitationRequest",
    Invitations.V1AcceptInvitationResponse,
    "V1AcceptInvitationResponse",
    200,
  ),
  academicPost(
    "locateStudent",
    "/v1/students/locate",
    "student.locate",
    Family.V1LocateStudentRequest,
    "V1LocateStudentRequest",
    Family.V1LocateStudentResponse,
    "V1LocateStudentResponse",
    200,
  ),
  academicPost(
    "requestGuardianLink",
    "/v1/guardian-links",
    "guardian_link.request",
    Family.V1RequestGuardianLinkRequest,
    "V1RequestGuardianLinkRequest",
    Family.V1GuardianLink,
    "V1GuardianLink",
    201,
  ),
  academicPost(
    "verifyGuardianLink",
    "/v1/guardian-links/{guardianLinkId}/verify",
    "guardian_link.verify",
    Family.V1VerifyGuardianLinkRequest,
    "V1VerifyGuardianLinkRequest",
    Family.V1GuardianLink,
    "V1GuardianLink",
    200,
    guardianLinkParams(),
  ),
  academicPost(
    "revokeGuardianLink",
    "/v1/guardian-links/{guardianLinkId}/revoke",
    "guardian_link.revoke",
    Family.V1RevokeGuardianLinkRequest,
    "V1RevokeGuardianLinkRequest",
    Family.V1GuardianLink,
    "V1GuardianLink",
    200,
    guardianLinkParams(),
  ),
  academicGet(
    "listConversations",
    "/v1/conversations",
    "conversation.list",
    Communications.V1ConversationPage,
    "V1ConversationPage",
    undefined,
    Academic.V1PageQuery,
  ),
  academicPost(
    "createConversation",
    "/v1/conversations",
    "conversation.create",
    Communications.V1CreateConversationRequest,
    "V1CreateConversationRequest",
    Communications.V1Conversation,
    "V1Conversation",
    201,
  ),
  academicGet(
    "listMessages",
    "/v1/conversations/{conversationId}/messages",
    "message.list",
    Communications.V1MessagePage,
    "V1MessagePage",
    conversationParams(),
    Academic.V1PageQuery,
  ),
  academicPost(
    "sendMessage",
    "/v1/conversations/{conversationId}/messages",
    "message.send",
    Communications.V1SendMessageRequest,
    "V1SendMessageRequest",
    Communications.V1Message,
    "V1Message",
    201,
    conversationParams(),
  ),
  academicPost(
    "createAnnouncement",
    "/v1/announcements",
    "announcement.create",
    Communications.V1CreateAnnouncementRequest,
    "V1CreateAnnouncementRequest",
    Communications.V1Announcement,
    "V1Announcement",
    201,
  ),
  academicGet(
    "listAnnouncements",
    "/v1/announcements",
    "announcement.list",
    Communications.V1AnnouncementPage,
    "V1AnnouncementPage",
    undefined,
    Academic.V1PageQuery,
  ),
  academicPost(
    "requestMeeting",
    "/v1/classrooms/{classroomId}/meetings",
    "meeting.request",
    Meetings.V1RequestMeetingRequest,
    "V1RequestMeetingRequest",
    Meetings.V1Meeting,
    "V1Meeting",
    201,
    classroomParams(),
  ),
  academicPost(
    "cancelMeeting",
    "/v1/meetings/{meetingId}/cancel",
    "meeting.cancel",
    Meetings.V1CancelMeetingRequest,
    "V1CancelMeetingRequest",
    Meetings.V1Meeting,
    "V1Meeting",
    200,
    meetingParams(),
  ),
  academicGet(
    "getMeetingStatus",
    "/v1/meetings/{meetingId}",
    "meeting.status",
    Meetings.V1MeetingStatusResponse,
    "V1MeetingStatusResponse",
    meetingParams(),
  ),
  academicGet(
    "listNotifications",
    "/v1/notifications",
    "notification.list",
    Notifications.V1NotificationPage,
    "V1NotificationPage",
    undefined,
    Academic.V1PageQuery,
  ),
  academicGet(
    "getUnreadCount",
    "/v1/notifications/unread-count",
    "notification.list",
    Notifications.V1UnreadCountResponse,
    "V1UnreadCountResponse",
  ),
  academicPost(
    "markNotificationsRead",
    "/v1/notifications/mark-read",
    "notification.mark_read",
    Notifications.V1MarkNotificationsReadRequest,
    "V1MarkNotificationsReadRequest",
    Notifications.V1MarkNotificationsReadResponse,
    "V1MarkNotificationsReadResponse",
    200,
  ),
  academicGet(
    "getNotificationPreferences",
    "/v1/notifications/preferences",
    "notification.preferences.read",
    Notifications.V1NotificationPreferencesResponse,
    "V1NotificationPreferencesResponse",
  ),
  academicPost(
    "updateNotificationPreferences",
    "/v1/notifications/preferences",
    "notification.preferences.write",
    Notifications.V1UpdateNotificationPreferenceRequest,
    "V1UpdateNotificationPreferenceRequest",
    Notifications.V1NotificationPreference,
    "V1NotificationPreference",
    200,
  ),
  academicPost(
    "updateProfile",
    "/v1/account/profile",
    "account.profile.write",
    Account.V1UpdateProfileRequest,
    "V1UpdateProfileRequest",
    Account.V1ProfileResponse,
    "V1ProfileResponse",
    200,
  ),
  academicPost(
    "requestDataExport",
    "/v1/account/export-request",
    "account.export.request",
    Account.V1RequestDataExportRequest,
    "V1RequestDataExportRequest",
    Account.V1DataExportRequest,
    "V1DataExportRequest",
    201,
  ),
  academicGet(
    "getExportStatus",
    "/v1/account/export-status",
    "account.export.status",
    Account.V1ExportStatusResponse,
    "V1ExportStatusResponse",
  ),
  academicPost(
    "requestSupportAccess",
    "/internal/support-access",
    "support_access.request",
    SupportAccess.V1RequestSupportAccessRequest,
    "V1RequestSupportAccessRequest",
    SupportAccess.V1SupportAccessGrant,
    "V1SupportAccessGrant",
    201,
  ),
  academicPost(
    "approveSupportAccess",
    "/internal/support-access/{supportGrantId}/approve",
    "support_access.approve",
    SupportAccess.V1SupportAccessLifecycleRequest,
    "V1SupportAccessLifecycleRequest",
    SupportAccess.V1SupportAccessGrant,
    "V1SupportAccessGrant",
    200,
    supportGrantParams(),
  ),
  academicPost(
    "startSupportAccess",
    "/internal/support-access/{supportGrantId}/start",
    "support_access.start",
    SupportAccess.V1SupportAccessLifecycleRequest,
    "V1SupportAccessLifecycleRequest",
    SupportAccess.V1SupportAccessGrant,
    "V1SupportAccessGrant",
    200,
    supportGrantParams(),
  ),
  academicPost(
    "revokeSupportAccess",
    "/internal/support-access/{supportGrantId}/revoke",
    "support_access.revoke",
    SupportAccess.V1RevokeSupportAccessRequest,
    "V1RevokeSupportAccessRequest",
    SupportAccess.V1SupportAccessGrant,
    "V1SupportAccessGrant",
    200,
    supportGrantParams(),
  ),
  academicGet(
    "listSupportAccessGrants",
    "/internal/support-access",
    "support_access.list",
    SupportAccess.V1SupportAccessGrantPage,
    "V1SupportAccessGrantPage",
    undefined,
    Academic.V1PageQuery,
  ),
  // Appended rather than inserted: every other module's slice() bound is a
  // fixed numeric range into this array (see school-admin/routes.ts and
  // friends), so a new entry always lands at the end. createTerm/
  // createStudent close a real gap API-041 shipped with: createClassroom
  // requires an existing 'active'/'planned' term and enrollStudent requires
  // an existing student row, and until now nothing in the catalogue could
  // create either - a freshly provisioned school could never actually reach
  // a working classroom. Found writing the S9 reviewer-tenant seed script,
  // which is exactly the "fresh school, real commands, no local-only state"
  // path this gap would otherwise have hidden from indefinitely.
  academicPost(
    "createTerm",
    "/v1/schools/{schoolId}/terms",
    "term.create",
    SchoolAdmin.V1CreateTermRequest,
    "V1CreateTermRequest",
    Academic.V1Term,
    "V1Term",
    201,
    schoolParams(),
  ),
  academicPost(
    "createStudent",
    "/v1/schools/{schoolId}/students",
    "student.create",
    SchoolAdmin.V1CreateStudentRequest,
    "V1CreateStudentRequest",
    SchoolAdmin.V1SchoolStudent,
    "V1SchoolStudent",
    201,
    schoolParams(),
  ),
  // -----------------------------------------------------------------------
  // SAFE-043 safety & safeguarding (appended at the end). Three clusters:
  // reporter-facing reporting/blocks, then the internal moderation cluster
  // (queue, triage, resolve, escalate, evidence, holds), then moderator
  // JIT-access grants. Reporting and blocks are self-scoped; every
  // moderation read/write is additionally school-scoped and enforcement of
  // that scope lives in the SQL dispatcher's safe043_can_access_* guards.
  // -----------------------------------------------------------------------
  academicGet(
    "getContentControls",
    "/v1/control-panel/content-controls/{schoolId}",
    "content_controls.read",
    Safety.V1ContentControls,
    "V1ContentControls",
    schoolParams(),
  ),
  academicPost(
    "updateContentControls",
    "/v1/control-panel/content-controls/{schoolId}",
    "content_controls.write",
    Safety.V1UpdateContentControlsRequest,
    "V1UpdateContentControlsRequest",
    Safety.V1ContentControls,
    "V1ContentControls",
    200,
    schoolParams(),
  ),
  academicPost(
    "createReport",
    "/v1/reports",
    "report.create",
    Safety.V1CreateReportRequest,
    "V1CreateReportRequest",
    Safety.V1Report,
    "V1Report",
    201,
  ),
  academicGet(
    "listReports",
    "/v1/reports",
    "report.read",
    Safety.V1ReportPage,
    "V1ReportPage",
    undefined,
    Academic.V1PageQuery,
  ),
  academicGet(
    "getReport",
    "/v1/reports/{reportId}",
    "report.read",
    Safety.V1Report,
    "V1Report",
    reportParams(),
  ),
  academicPost(
    "appealReport",
    "/v1/reports/{reportId}/appeal",
    "report.appeal",
    Safety.V1AppealReportRequest,
    "V1AppealReportRequest",
    Safety.V1Report,
    "V1Report",
    200,
    reportParams(),
  ),
  academicPost(
    "createBlock",
    "/v1/blocks",
    "block.manage",
    Safety.V1CreateBlockRequest,
    "V1CreateBlockRequest",
    Safety.V1Block,
    "V1Block",
    201,
  ),
  {
    method: "get",
    path: "/v1/blocks",
    operationId: "listBlocks",
    summary: "listBlocks",
    permission: "block.manage",
    idempotency: "none",
    response: Safety.V1BlockPage,
    responseSchema: "V1BlockPage",
    query: Safety.V1SchoolScopeQuery,
    querySchema: "V1SchoolScopeQuery",
  },
  academicPost(
    "unblockUser",
    "/v1/blocks/{blockId}/unblock",
    "block.manage",
    Safety.V1UnblockUserRequest,
    "V1UnblockUserRequest",
    Safety.V1Block,
    "V1Block",
    200,
    blockParams(),
  ),
  {
    method: "get",
    path: "/internal/moderation/overview",
    operationId: "getModerationOverview",
    summary: "getModerationOverview",
    permission: "moderation.overview.read",
    idempotency: "none",
    response: Safety.V1ModerationOverview,
    responseSchema: "V1ModerationOverview",
    query: Safety.V1SchoolIdQuery,
    querySchema: "V1SchoolIdQuery",
  },
  {
    method: "get",
    path: "/internal/moderation/queue",
    operationId: "listModerationQueue",
    summary: "listModerationQueue",
    permission: "moderation.queue.read",
    idempotency: "none",
    response: Safety.V1ModerationQueuePage,
    responseSchema: "V1ModerationQueuePage",
    query: Safety.V1ModerationQueueQuery,
    querySchema: "V1ModerationQueueQuery",
  },
  academicGet(
    "getModerationReport",
    "/internal/moderation/reports/{reportId}",
    "moderation.report.read",
    Safety.V1ModerationReport,
    "V1ModerationReport",
    reportParams(),
  ),
  academicPost(
    "triageReport",
    "/internal/moderation/reports/{reportId}/triage",
    "moderation.triage",
    Safety.V1ReportLifecycleRequest,
    "V1ReportLifecycleRequest",
    Safety.V1ModerationReport,
    "V1ModerationReport",
    200,
    reportParams(),
  ),
  academicPost(
    "resolveReport",
    "/internal/moderation/reports/{reportId}/resolve",
    "moderation.resolve",
    Safety.V1ResolveReportRequest,
    "V1ResolveReportRequest",
    Safety.V1ModerationReport,
    "V1ModerationReport",
    200,
    reportParams(),
  ),
  academicPost(
    "escalateReport",
    "/internal/moderation/reports/{reportId}/escalate",
    "moderation.escalate",
    Safety.V1EscalateReportRequest,
    "V1EscalateReportRequest",
    Safety.V1ModerationReport,
    "V1ModerationReport",
    200,
    reportParams(),
  ),
  academicPost(
    "addReportEvidence",
    "/internal/moderation/reports/{reportId}/evidence",
    "moderation.evidence.write",
    Safety.V1AddReportEvidenceRequest,
    "V1AddReportEvidenceRequest",
    Safety.V1ModerationReport,
    "V1ModerationReport",
    201,
    reportParams(),
  ),
  academicPost(
    "holdReport",
    "/internal/moderation/reports/{reportId}/hold",
    "moderation.hold",
    Safety.V1HoldReportRequest,
    "V1HoldReportRequest",
    Safety.V1LegalHold,
    "V1LegalHold",
    201,
    reportParams(),
  ),
  academicPost(
    "releaseLegalHold",
    "/internal/legal-holds/{legalHoldId}/release",
    "moderation.hold",
    Safety.V1ReleaseLegalHoldRequest,
    "V1ReleaseLegalHoldRequest",
    Safety.V1LegalHold,
    "V1LegalHold",
    200,
    legalHoldParams(),
  ),
  academicPost(
    "requestModerationAccess",
    "/internal/moderation/access",
    "moderation.access.request",
    Safety.V1RequestModerationAccessRequest,
    "V1RequestModerationAccessRequest",
    Safety.V1ModerationAccessGrant,
    "V1ModerationAccessGrant",
    201,
  ),
  academicPost(
    "approveModerationAccess",
    "/internal/moderation/access/{moderationGrantId}/approve",
    "moderation.access.approve",
    Safety.V1ModerationAccessLifecycleRequest,
    "V1ModerationAccessLifecycleRequest",
    Safety.V1ModerationAccessGrant,
    "V1ModerationAccessGrant",
    200,
    moderationGrantParams(),
  ),
  academicPost(
    "startModerationAccess",
    "/internal/moderation/access/{moderationGrantId}/start",
    "moderation.access.start",
    Safety.V1ModerationAccessLifecycleRequest,
    "V1ModerationAccessLifecycleRequest",
    Safety.V1ModerationAccessGrant,
    "V1ModerationAccessGrant",
    200,
    moderationGrantParams(),
  ),
  academicPost(
    "revokeModerationAccess",
    "/internal/moderation/access/{moderationGrantId}/revoke",
    "moderation.access.revoke",
    Safety.V1RevokeModerationAccessRequest,
    "V1RevokeModerationAccessRequest",
    Safety.V1ModerationAccessGrant,
    "V1ModerationAccessGrant",
    200,
    moderationGrantParams(),
  ),
  {
    method: "get",
    path: "/internal/moderation/access",
    operationId: "listModerationAccess",
    summary: "listModerationAccess",
    permission: "moderation.access.list",
    idempotency: "none",
    response: Safety.V1ModerationAccessGrantPage,
    responseSchema: "V1ModerationAccessGrantPage",
    query: Safety.V1ModerationAccessQuery,
    querySchema: "V1ModerationAccessQuery",
  },
  academicPost(
    "createUploadIntent",
    "/v1/uploads",
    "upload.intent.create",
    Files.V1CreateUploadIntentRequest,
    "V1CreateUploadIntentRequest",
    Files.V1CreateUploadIntentResponse,
    "V1CreateUploadIntentResponse",
    201,
  ),
  academicGet(
    "getUploadStatus",
    "/v1/uploads/{uploadId}",
    "upload.read",
    Files.V1UploadSession,
    "V1UploadSession",
    uploadParams(),
  ),
  academicPost(
    "completeUpload",
    "/v1/uploads/{uploadId}/complete",
    "upload.complete",
    Files.V1CompleteUploadRequest,
    "V1CompleteUploadRequest",
    Files.V1CompleteUploadResponse,
    "V1CompleteUploadResponse",
    200,
    uploadParams(),
  ),
  academicGet(
    "getFileStatus",
    "/v1/files/{fileId}",
    "file.read",
    Files.V1File,
    "V1File",
    fileParams(),
  ),
  academicPost(
    "createFileDownloadIntent",
    "/v1/files/{fileId}/download-intent",
    "file.download",
    Files.V1DownloadIntentRequest,
    "V1DownloadIntentRequest",
    Files.V1DownloadIntentResponse,
    "V1DownloadIntentResponse",
    200,
    fileParams(),
  ),
  academicPost(
    "publishFile",
    "/v1/files/{fileId}/publish",
    "file.publish",
    Files.V1PublishFileRequest,
    "V1PublishFileRequest",
    Files.V1PublishFileResponse,
    "V1PublishFileResponse",
    201,
    fileParams(),
  ),
] as const satisfies readonly V1RouteContract[];

function params(key: string) {
  return z.strictObject({ [key]: z.string().uuid() });
}
function schoolParams() {
  return params("schoolId");
}
function classroomParams() {
  return params("classroomId");
}
function resourceParams() {
  return params("resourceId");
}
function assignmentParams() {
  return params("assignmentId");
}
function assessmentParams() {
  return params("assessmentId");
}
function gradeParams() {
  return params("gradeResultId");
}
function membershipParams() {
  return params("membershipId");
}
function invitationParams() {
  return params("invitationId");
}
function guardianLinkParams() {
  return params("guardianLinkId");
}
function conversationParams() {
  return params("conversationId");
}
function meetingParams() {
  return params("meetingId");
}
function supportGrantParams() {
  return params("supportGrantId");
}
function reportParams() {
  return params("reportId");
}
function blockParams() {
  return params("blockId");
}
function legalHoldParams() {
  return params("legalHoldId");
}
function moderationGrantParams() {
  return params("moderationGrantId");
}
function uploadParams() {
  return params("uploadId");
}
function fileParams() {
  return params("fileId");
}

function academicGet(
  operationId: string,
  path: string,
  permission: string,
  response: z.ZodType,
  responseSchema: string,
  paramsSchema?: z.ZodType,
  query?: z.ZodType,
): V1RouteContract {
  return {
    method: "get",
    path,
    operationId,
    summary: operationId,
    permission,
    idempotency: "none",
    response,
    responseSchema,
    ...(paramsSchema ? { params: paramsSchema } : {}),
    ...(query ? { query, querySchema: "V1PageQuery" } : {}),
  };
}

function academicPost(
  operationId: string,
  path: string,
  permission: string,
  request: z.ZodType,
  requestSchema: string,
  response: z.ZodType,
  responseSchema: string,
  successStatus: 200 | 201,
  paramsSchema?: z.ZodType,
): V1RouteContract {
  return {
    method: "post",
    path,
    operationId,
    summary: operationId,
    permission,
    idempotency: "required",
    successStatus,
    request,
    requestSchema,
    response,
    responseSchema,
    ...(paramsSchema ? { params: paramsSchema } : {}),
  };
}

export type V1OperationId = (typeof V1_ROUTE_CATALOGUE)[number]["operationId"];

export function v1Route(
  operationId: V1OperationId,
): (typeof V1_ROUTE_CATALOGUE)[number] {
  const route = V1_ROUTE_CATALOGUE.find((entry) =>
    entry.operationId === operationId
  );
  if (!route) throw new Error(`Unknown v1 operation: ${operationId}`);
  return route;
}
