project_id = "studafy"

[api]
enabled = true
schemas = ["public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[auth]
enabled = true
site_url = "io.studafy.app://login-callback"

[storage]
enabled = true
file_size_limit = "50MiB"
