import '../contracts/v1_client.generated.dart';
import '../../core/runtime_environment.dart';

String billingEnvironmentName(StudafyEnvironment environment) =>
    switch (environment) {
      StudafyEnvironment.synthetic => 'synthetic',
      StudafyEnvironment.development => 'development',
      StudafyEnvironment.staging => 'staging',
      StudafyEnvironment.production => 'production',
    };

class V1BillingProduct {
  const V1BillingProduct({
    required this.featureKey,
    required this.platform,
    required this.storeProductId,
  });

  final String featureKey;
  final String platform;
  final String storeProductId;

  factory V1BillingProduct.fromJson(Map<String, dynamic> json) =>
      V1BillingProduct(
        featureKey: json['featureKey'] as String,
        platform: json['platform'] as String,
        storeProductId: json['storeProductId'] as String,
      );
}

class V1BillingSelfPurchaseStatus {
  const V1BillingSelfPurchaseStatus({
    required this.schoolId,
    required this.selfPurchaseEnabled,
  });

  final String schoolId;
  final bool selfPurchaseEnabled;

  factory V1BillingSelfPurchaseStatus.fromJson(Map<String, dynamic> json) =>
      V1BillingSelfPurchaseStatus(
        schoolId: json['schoolId'] as String,
        selfPurchaseEnabled: json['selfPurchaseEnabled'] as bool,
      );
}

class V1BillingCatalogue {
  const V1BillingCatalogue({
    required this.products,
    required this.selfPurchase,
  });

  final List<V1BillingProduct> products;
  final List<V1BillingSelfPurchaseStatus> selfPurchase;

  factory V1BillingCatalogue.fromJson(
    Map<String, dynamic> json,
  ) => V1BillingCatalogue(
    products: (json['products'] as List<dynamic>)
        .map((row) => V1BillingProduct.fromJson(row as Map<String, dynamic>))
        .toList(),
    selfPurchase: (json['selfPurchase'] as List<dynamic>)
        .map(
          (row) =>
              V1BillingSelfPurchaseStatus.fromJson(row as Map<String, dynamic>),
        )
        .toList(),
  );
}

class V1ParentalGateChallenge {
  const V1ParentalGateChallenge({required this.token, required this.question});

  final String token;
  final String question;

  factory V1ParentalGateChallenge.fromJson(Map<String, dynamic> json) =>
      V1ParentalGateChallenge(
        token: json['token'] as String,
        question: json['question'] as String,
      );
}

class V1ParentalGateAnswer {
  const V1ParentalGateAnswer({required this.token, required this.answer});

  final String token;
  final int answer;

  Map<String, Object?> toJson() => {'token': token, 'answer': answer};
}

class V1SubmitPurchaseOutcome {
  const V1SubmitPurchaseOutcome({
    required this.featureKey,
    required this.derivation,
  });

  final String featureKey;
  final String derivation;

  factory V1SubmitPurchaseOutcome.fromJson(Map<String, dynamic> json) =>
      V1SubmitPurchaseOutcome(
        featureKey: json['featureKey'] as String,
        derivation: json['derivation'] as String,
      );
}

class V1RestoreOutcome {
  const V1RestoreOutcome({
    required this.restored,
    this.featureKey,
    this.derivation,
  });

  final bool restored;
  final String? featureKey;
  final String? derivation;

  factory V1RestoreOutcome.fromJson(Map<String, dynamic> json) =>
      V1RestoreOutcome(
        restored: json['restored'] as bool? ?? false,
        featureKey: json['featureKey'] as String?,
        derivation: json['derivation'] as String?,
      );
}

class V1EntitlementRow {
  const V1EntitlementRow({
    required this.featureKey,
    required this.status,
    required this.startsAt,
    this.endsAt,
  });

  final String featureKey;
  final String status;
  final DateTime startsAt;
  final DateTime? endsAt;

  bool get grantsAccess => status == 'active' || status == 'grace_period';

  factory V1EntitlementRow.fromJson(Map<String, dynamic> json) =>
      V1EntitlementRow(
        featureKey: json['featureKey'] as String,
        status: json['status'] as String,
        startsAt: DateTime.parse(json['startsAt'] as String),
        endsAt: json['endsAt'] == null
            ? null
            : DateTime.parse(json['endsAt'] as String),
      );
}

/// Typed client for the /v1/billing/* endpoints (PAY-071). Separate from the
/// generated `/v1` client because the OpenAPI spec is regenerated by a
/// Dart-formatter step that this build environment does not run; the two
/// clients share the same [V1JsonTransport] so there is exactly one HTTP
/// path, one auth refresh, one idempotency policy.
class V1BillingApi {
  V1BillingApi(this._transport, {required this.environment});

  final V1JsonTransport _transport;
  final String environment;

  Future<V1BillingCatalogue> catalogue() async => V1BillingCatalogue.fromJson(
    await _transport.get('/v1/billing/catalogue'),
  );

  Future<V1ParentalGateChallenge> parentalGate() async =>
      V1ParentalGateChallenge.fromJson(
        await _transport.get('/v1/billing/parental-gate'),
      );

  Future<V1SubmitPurchaseOutcome> submitPurchase({
    required String platform,
    required String storeProductId,
    required String featureKey,
    required String verificationPayload,
    String? beneficiaryStudentId,
    V1ParentalGateAnswer? parentalGate,
    required String idempotencyKey,
  }) async {
    final response = await _transport.post(
      '/v1/billing/purchases',
      {
        'platform': platform,
        'environment': environment,
        'storeProductId': storeProductId,
        'productFeatureKey': featureKey,
        'verificationPayload': verificationPayload,
        'beneficiaryStudentId': ?beneficiaryStudentId,
        if (parentalGate != null) 'parentalGate': parentalGate.toJson(),
      },
      idempotencyKey: idempotencyKey,
      requiresIdempotency: true,
    );
    return V1SubmitPurchaseOutcome.fromJson(response);
  }

  Future<V1RestoreOutcome> restorePurchase({
    required String platform,
    required String storeProductId,
    required String featureKey,
    required String verificationPayload,
    String? beneficiaryStudentId,
    V1ParentalGateAnswer? parentalGate,
    required String idempotencyKey,
  }) async {
    final response = await _transport.post(
      '/v1/billing/restore',
      {
        'platform': platform,
        'environment': environment,
        'storeProductId': storeProductId,
        'productFeatureKey': featureKey,
        'verificationPayload': verificationPayload,
        'beneficiaryStudentId': ?beneficiaryStudentId,
        if (parentalGate != null) 'parentalGate': parentalGate.toJson(),
      },
      idempotencyKey: idempotencyKey,
      requiresIdempotency: true,
    );
    return V1RestoreOutcome.fromJson(response);
  }

  Future<List<V1EntitlementRow>> entitlements() async {
    final response = await _transport.get('/v1/billing/entitlements');
    return (response['entitlements'] as List<dynamic>)
        .map((row) => V1EntitlementRow.fromJson(row as Map<String, dynamic>))
        .toList();
  }
}
